eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.10:8761/eureka/,http://192.168.1.10:8762/eureka/
  #instance: clientName
spring:
  application:
    name: client
server:
  port: 8080
evn: dev
